[2024-04-25 23:25:09,293: INFO: main: Welcome to our custom logging]
[2024-04-27 17:45:32,322: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-27 17:45:32,337: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-27 17:48:16,096: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-27 17:48:16,098: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-27 17:48:16,100: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-04-27 17:49:58,710: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-27 17:49:58,712: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-27 17:49:58,714: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-04-27 17:52:23,043: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-27 17:52:23,044: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-27 17:52:23,046: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-04-27 17:52:23,048: INFO: common: created directory at: artifacts]
[2024-04-27 18:02:45,986: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-27 18:02:45,988: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-27 18:02:45,990: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-04-27 18:02:45,991: INFO: common: created directory at: artifacts]
[2024-04-27 18:02:45,993: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-27 18:03:21,340: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-27 18:03:21,342: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-27 18:03:21,344: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-04-27 18:03:21,345: INFO: common: created directory at: artifacts]
[2024-04-27 18:03:21,347: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-27 18:03:22,509: INFO: 1770394596: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: C4DC:207C7D:1AA484:238C55:662CF08E
Accept-Ranges: bytes
Date: Sat, 27 Apr 2024 12:33:21 GMT
Via: 1.1 varnish
X-Served-By: cache-bom4736-BOM
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1714221201.340102,VS0,VE310
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 8c49b66807452666cb35cddef826bbb67edd96a7
Expires: Sat, 27 Apr 2024 12:38:21 GMT
Source-Age: 0

]
[2024-04-27 18:04:21,963: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-27 18:04:21,965: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-27 18:04:21,967: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-04-27 18:04:21,969: INFO: common: created directory at: artifacts]
[2024-04-27 18:04:21,970: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-27 18:04:21,972: INFO: 1770394596: File already exists of size: ~23 KB]
[2024-04-27 18:04:39,744: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-27 18:04:39,746: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-27 18:04:39,748: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-04-27 18:04:39,749: INFO: common: created directory at: artifacts]
[2024-04-27 18:04:39,751: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-27 18:04:39,752: INFO: 1770394596: File already exists of size: ~23 KB]
[2024-04-27 18:05:04,757: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-27 18:05:04,759: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-27 18:05:04,762: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-04-27 18:05:04,763: INFO: common: created directory at: artifacts]
[2024-04-27 18:05:04,765: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-27 18:05:04,767: INFO: 4165007749: File already exists of size: ~23 KB]
[2024-04-27 19:23:31,687: INFO: main: Welcome to our custom logging]
[2024-04-27 19:36:36,161: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<]
[2024-04-27 19:36:36,161: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-27 19:36:36,179: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-27 19:36:36,180: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-04-27 19:36:36,181: ERROR: main: name 'config' is not defined]
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    obj.main()
  File "D:\1 Learning\project\End-to-End-ML-Project-with-mlflow\src\mlproject\pipeline\stage_01_data_ingestion.py", line 20, in main
    raise e
  File "D:\1 Learning\project\End-to-End-ML-Project-with-mlflow\src\mlproject\pipeline\stage_01_data_ingestion.py", line 14, in main
    config = ConfigurationManager()
  File "D:\1 Learning\project\End-to-End-ML-Project-with-mlflow\src\mlproject\config\configuration.py", line 18, in __init__
    create_directories([config.artifacts_root])
NameError: name 'config' is not defined
[2024-04-27 19:36:55,710: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<]
[2024-04-27 19:36:55,710: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-27 19:36:55,710: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-27 19:36:55,710: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-04-27 19:36:55,710: ERROR: main: name 'config' is not defined]
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    obj.main()
  File "D:\1 Learning\project\End-to-End-ML-Project-with-mlflow\src\mlproject\pipeline\stage_01_data_ingestion.py", line 20, in main
    raise e
  File "D:\1 Learning\project\End-to-End-ML-Project-with-mlflow\src\mlproject\pipeline\stage_01_data_ingestion.py", line 14, in main
    config = ConfigurationManager()
  File "D:\1 Learning\project\End-to-End-ML-Project-with-mlflow\src\mlproject\config\configuration.py", line 18, in __init__
    create_directories([config.artifacts_root])
NameError: name 'config' is not defined
[2024-04-27 19:44:02,487: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<]
[2024-04-27 19:44:02,488: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-27 19:44:02,488: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-27 19:44:02,488: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-04-27 19:44:02,494: INFO: common: created directory at: artifacts]
[2024-04-27 19:44:02,495: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-27 19:44:02,496: ERROR: main: __init__() got an unexpected keyword argument 'source_URL']
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    obj.main()
  File "D:\1 Learning\project\End-to-End-ML-Project-with-mlflow\src\mlproject\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion_config = config.get_data_ingestion_config()
  File "D:\1 Learning\project\End-to-End-ML-Project-with-mlflow\src\mlproject\config\configuration.py", line 29, in get_data_ingestion_config
    unzip_dir=config.unzip_dir,
TypeError: __init__() got an unexpected keyword argument 'source_URL'
[2024-04-27 19:51:42,162: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<]
[2024-04-27 19:51:42,178: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-27 19:51:42,178: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-27 19:51:42,178: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-04-27 19:51:42,178: INFO: common: created directory at: artifacts]
[2024-04-27 19:51:42,178: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-27 19:51:42,178: ERROR: main: __init__() got an unexpected keyword argument 'source_URL']
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    obj.main()
  File "D:\1 Learning\project\End-to-End-ML-Project-with-mlflow\src\mlproject\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion_config = config.get_data_ingestion_config()
  File "D:\1 Learning\project\End-to-End-ML-Project-with-mlflow\src\mlproject\config\configuration.py", line 29, in get_data_ingestion_config
    unzip_dir=config.unzip_dir,
TypeError: __init__() got an unexpected keyword argument 'source_URL'
[2024-04-27 19:52:07,382: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<]
[2024-04-27 19:52:07,382: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-27 19:52:07,382: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-27 19:52:07,382: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-04-27 19:52:07,382: INFO: common: created directory at: artifacts]
[2024-04-27 19:52:07,382: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-27 19:52:08,545: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 22A8:216382:1B485E:24843B:662D0A0B
Accept-Ranges: bytes
Date: Sat, 27 Apr 2024 14:22:07 GMT
Via: 1.1 varnish
X-Served-By: cache-bom4741-BOM
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1714227728.726396,VS0,VE270
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: db0b59b00279fcecb7f56d7e32cdcd4a5f2f48a8
Expires: Sat, 27 Apr 2024 14:27:07 GMT
Source-Age: 0

]
[2024-04-27 19:52:08,545: ERROR: main: 'DataIngestion' object has no attribute 'extract_zip_file']
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    obj.main()
  File "D:\1 Learning\project\End-to-End-ML-Project-with-mlflow\src\mlproject\pipeline\stage_01_data_ingestion.py", line 18, in main
    data_ingestion.extract_zip_file()
AttributeError: 'DataIngestion' object has no attribute 'extract_zip_file'
[2024-04-27 19:52:59,043: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<]
[2024-04-27 19:52:59,043: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-27 19:52:59,043: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-27 19:52:59,043: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-04-27 19:52:59,043: INFO: common: created directory at: artifacts]
[2024-04-27 19:52:59,043: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-27 19:52:59,043: INFO: data_ingestion: File already exists of size: ~23 KB]
[2024-04-27 19:52:59,059: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<]
